# Generated by Django 3.2.5 on 2021-07-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hydjobs',
            new_name='hyjobs',
        ),
    ]
