# Generated by Django 3.2.5 on 2021-07-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_hydjobs_hyjobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='delhijobs',
            new_name='deljobs',
        ),
    ]
