# Generated by Django 3.2.5 on 2021-07-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_rename_delhijobs_deljobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mumbaijobs',
            new_name='mumjobs',
        ),
    ]
